require("fengwk.plugins.workspaces")
require("fengwk.plugins.aerial")
require("fengwk.plugins.comment")
require("fengwk.plugins.gitsigns")
require("fengwk.plugins.hop")
require("fengwk.plugins.indent-blankline")
-- require("fengwk.plugins.lsp_lines")
require("fengwk.plugins.lualine")
require("fengwk.plugins.markdown-preview")
require("fengwk.plugins.md-img-paste")
require("fengwk.plugins.nvim-autopairs")
require("fengwk.plugins.nvim-cmp")
require("fengwk.plugins.nvim-colorizer")
require("fengwk.plugins.nvim-surround")
require("fengwk.plugins.nvim-tree")
-- require("fengwk.plugins.treesitter")
-- require("fengwk.plugins.nvim-treesitter-textobjects")
require("fengwk.plugins.telescope")
require("fengwk.plugins.toggleterm")
require("fengwk.plugins.translator")
require("fengwk.plugins.venn")
require("fengwk.plugins.vim-illuminate")
require("fengwk.plugins.vim-vsnip")
require("fengwk.plugins.which-key")
require("fengwk.plugins.wildfire")
require("fengwk.plugins.lsp")